Python program using Python Lists using profiling

In [21]:
import cProfile

# Function to add two matrices
def matrix_add(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# Function to subtract two matrices
def matrix_subtract(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# Function to multiply two matrices
def matrix_multiply(A, B):
    return [[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]

def main():
    # Define matrices A, B, and C
    A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
    B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
    C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

    # Perform matrix operations
    add_result = matrix_add(A, B)
    subtract_result = matrix_subtract(A, B)
    multiply_result = matrix_multiply(A, B)

    # Print results
    print("A + B =", add_result)
    print("A - B =", subtract_result)
    print("A * B =", multiply_result)

# Run the main function with profiling
cProfile.run('main()')



A + B = [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]
A - B = [[0.6593, 0.24670000000000014, 0.11070000000000002], [0.10110000000000019, 0.34560000000000013, 0.5754000000000001], [0.024699999999999944, 1.5478000000000003, 0.7852999999999994]]
A * B = [[22.43066479, 26.85280533, 39.53569494], [18.736056750000003, 23.61065602, 38.8279668], [16.108972989999998, 20.754939779999997, 43.42603136]]
         174 function calls in 0.003 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 3302188124.py:12(matrix_multiply)
       36    0.000    0.000    0.000    0.000 3302188124.py:13(<genexpr>)
        1    0.000    0.000    0.000    0.000 3302188124.py:13(<listcomp>)
        1    0.000    0.000    0.003    0.003 3302188124.py:15(main)
        1    0.000    0.000    0.000    0.000 3302188124.py:4(matrix_add)
        3    0.000    0.000    0.000    0.00

Python program and NumPy using profiling

In [25]:

import cProfile

def main():
    # Define matrices A, B, and C using NumPy arrays
    A = np. array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
    B = np. array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
    C = np. array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

    # Perform matrix operations using NumPy functions
    add_result = np.add(A, B)  # Element-wise addition
    subtract_result = np.subtract(A, B)  # Element-wise subtraction
    multiply_result = np.dot(A, B)  # Matrix multiplication

    # Print results
    print("A + B =", add_result)
    print("A - B =", subtract_result)
    print("A * B =", multiply_result)

# Run the main function with profiling
cProfile.run('main()')


A + B = [[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]
A - B = [[0.6593 0.2467 0.1107]
 [0.1011 0.3456 0.5754]
 [0.0247 1.5478 0.7853]]
A * B = [[22.43066479 26.85280533 39.53569494]
 [18.73605675 23.61065602 38.8279668 ]
 [16.10897299 20.75493978 43.42603136]]
         928 function calls (892 primitive calls) in 0.004 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001    0.004    0.004 48581028.py:3(main)
        1    0.000    0.000    0.004    0.004 <string>:1(<module>)
        6    0.000    0.000    0.000    0.000 _ufunc_config.py:132(geterr)
        6    0.000    0.000    0.000    0.000 _ufunc_config.py:33(seterr)
        3    0.000    0.000    0.000    0.000 _ufunc_config.py:426(__init__)
        3    0.000    0.000    0.000    0.000 _ufunc_config.py:430(__enter__)
        3    0.000    0.000    0.000    0.000 _ufunc_config.py:435(__exit__)
       27    0.000 

Python Program and perform the following operations ?
I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}
II.	Iterate using a for loop
III.	Iterate using for loop and range
IV.	List Comprehension
V.	Enumerate
VI.	Iter function and next function
VII.	Map function
VIII.	Using zip
IX.	Using NumPy Module


In [1]:
import numpy as np
import cProfile

def main():
    # I. Create the list
    my_list = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

    # II. Iterate using a for loop
    print("II. Iterating using a for loop:")
    for item in my_list:
        print(item)

    # III. Iterate using for loop and range
    print("\nIII. Iterating using for loop and range:")
    for i in range(len(my_list)):
        print(f"Index {i}: {my_list[i]}")

    # IV. List Comprehension
    squared_list = [x**2 for x in my_list]  # Create a new list with squared values
    print("\nIV. List after squaring each element (using list comprehension):", squared_list)

    # V. Enumerate
    print("\nV. Using enumerate:")
    for index, value in enumerate(my_list):
        print(f"Index {index}: {value}")

    # VI. Iter function and next function
    print("\nVI. Using iter() and next():")
    iter_list = iter(my_list)  # Create an iterator object
    for _ in range(len(my_list)):
        print(next(iter_list))  # Get next item from iterator

    # VII. Map function
    def double(x):
        return x * 2
    doubled_list = list(map(double, my_list))  # Apply double function to each element
    print("\nVII. List after doubling each element (using map()):", doubled_list)

    # VIII. Using zip
    list1 = [1, 2, 3, 4, 5]
    list2 = ['a', 'b', 'c', 'd', 'e']
    zipped = list(zip(list1, list2))  # Combine elements from both lists
    print("\nVIII. Zipped lists:", zipped)

    # IX. Using NumPy Module
    np_array = np.array(my_list)  # Convert list to NumPy array
    print("\nIX. NumPy array:", np_array)
    print("Mean of the array:", np.mean(np_array))
    print("Standard deviation of the array:", np.std(np_array))

# Run the main function with profiling
cProfile.run('main()')


II. Iterating using a for loop:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456

III. Iterating using for loop and range:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456

IV. List after squaring each element (using list comprehension): [1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]

V. Using enumerate:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456

VI. Using iter() and next():
1225
4986
6789
7890
2345
6783
987
1234
8765
3456

VII. List after doubling each element (using map()): [2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]

VIII. Zipped lists: [(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]

IX. NumPy array: [1225 4986 6789 7890 2345 6783  987 1234 8765 3456]
Mean of the array: 4446.0
Standard deviation of the array: 2825.039504148570

Program to compute all the combinations and permutations 

In [3]:
from itertools import combinations, permutations
import cProfile

def main():
    # Define lists A, B, C, D, E
    A = [1, 2, 3]
    B = ['a', 'b', 'c']
    C = [True, False]
    D = [3.14, 2.71]
    E = ['x', 'y']

    all_lists = [A, B, C, D, E]

    # Compute combinations
    print("Combinations:")
    for i, lst in enumerate(all_lists):
        print(f"\nCombinations for list {chr(65+i)}:")
        for r in range(1, len(lst) + 1):
            combs = list(combinations(lst, r))  # Get all r-combinations
            print(f"  {r}-combinations: {combs}")

    # Compute permutations
    print("\nPermutations:")
    for i, lst in enumerate(all_lists):
        print(f"\nPermutations for list {chr(65+i)}:")
        perms = list(permutations(lst))  # Get all permutations
        print(f"  All permutations: {perms}")

# Run the main function with profiling
cProfile.run('main()')


Combinations:

Combinations for list A:
  1-combinations: [(1,), (2,), (3,)]
  2-combinations: [(1, 2), (1, 3), (2, 3)]
  3-combinations: [(1, 2, 3)]

Combinations for list B:
  1-combinations: [('a',), ('b',), ('c',)]
  2-combinations: [('a', 'b'), ('a', 'c'), ('b', 'c')]
  3-combinations: [('a', 'b', 'c')]

Combinations for list C:
  1-combinations: [(True,), (False,)]
  2-combinations: [(True, False)]

Combinations for list D:
  1-combinations: [(3.14,), (2.71,)]
  2-combinations: [(3.14, 2.71)]

Combinations for list E:
  1-combinations: [('x',), ('y',)]
  2-combinations: [('x', 'y')]

Permutations:

Permutations for list A:
  All permutations: [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

Permutations for list B:
  All permutations: [('a', 'b', 'c'), ('a', 'c', 'b'), ('b', 'a', 'c'), ('b', 'c', 'a'), ('c', 'a', 'b'), ('c', 'b', 'a')]

Permutations for list C:
  All permutations: [(True, False), (False, True)]

Permutations for list D:
  All permutations: [(3.

Itertools compute permutations and combinations 

In [5]:
from itertools import combinations, permutations
import cProfile

def main():
    # Define lists A, B, C, D, E
    A = [1, 2, 3]
    B = ['a', 'b', 'c']
    C = [True, False]
    D = [3.14, 2.71]
    E = ['x', 'y']

    all_lists = [A, B, C, D, E]

# Compute combinations using itertools (same as above, demonstrating itertools usage)
    print("\nCombinations using itertools:")
    for i, lst in enumerate(all_lists):
        print(f"\nCombinations for list {chr(65+i)}:")
        for r in range(1, len(lst) + 1):
            combs = list(combinations(lst, r))
            print(f"  {r}-combinations: {combs}")

    # Compute permutations using itertools (same as above, demonstrating itertools usage)
    print("\nPermutations using itertools:")
    for i, lst in enumerate(all_lists):
        print(f"\nPermutations for list {chr(65+i)}:")
        perms = list(permutations(lst))
        print(f"  All permutations: {perms}")

# Run the main function with profiling
cProfile.run('main()')




Combinations using itertools:

Combinations for list A:
  1-combinations: [(1,), (2,), (3,)]
  2-combinations: [(1, 2), (1, 3), (2, 3)]
  3-combinations: [(1, 2, 3)]

Combinations for list B:
  1-combinations: [('a',), ('b',), ('c',)]
  2-combinations: [('a', 'b'), ('a', 'c'), ('b', 'c')]
  3-combinations: [('a', 'b', 'c')]

Combinations for list C:
  1-combinations: [(True,), (False,)]
  2-combinations: [(True, False)]

Combinations for list D:
  1-combinations: [(3.14,), (2.71,)]
  2-combinations: [(3.14, 2.71)]

Combinations for list E:
  1-combinations: [('x',), ('y',)]
  2-combinations: [('x', 'y')]

Permutations using itertools:

Permutations for list A:
  All permutations: [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

Permutations for list B:
  All permutations: [('a', 'b', 'c'), ('a', 'c', 'b'), ('b', 'a', 'c'), ('b', 'c', 'a'), ('c', 'a', 'b'), ('c', 'b', 'a')]

Permutations for list C:
  All permutations: [(True, False), (False, True)]

Permutations for